name: Schedule Probe

on:
  workflow_dispatch:
  schedule:
    - cron: "2-59/5 * * * *"

jobs:
  probe:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - run: date -u
